version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: username
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: authDB

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080